### PR TITLE
Shared objects inheritance

### LINKED ISSUE #64: Ability to allow shared object inheritance
After their introduction, we found shared objects very useful in our configuration setup. Based on our experience working with shared objects, we would highly appreciate the availability of some kind of basic inheritance for shared object definition. Especially from the scala config perspective, this would reduce code duplicates when working with several shared object definitions that have one or more fields in common because one could pattern match against them. 

I have not thought about all details yet, because I'm unsure if this a feature that could be of interested to be included, but my first idea was something like:

```
#@define_pa
BaseModelConfig {
  uuids: [string]         
  scaling: double  
}

#@define
LoadModelConfig ex BaseModelConfig{
  modelBehaviour: string  
  reference: string       
}

#@define
FixedFeedInModelConfig ex BaseModelConfig
```

This would end up in either a sealed trait or an abstract class (whatever is easier) in the generated code (only thought about scala for now, maybe slightly different concept needs to be developed for java code):

```scala
  sealed trait BaseModelConfig {
    val scaling: scala.Double
    val uuids: scala.List[java.lang.String]
  }

  final case class LoadModelConfig(
                              scaling: Double,
                              uuids: List[String],
                              modelBehaviour: java.lang.String,
                              reference: java.lang.String
                            ) extends BaseModelConfig

  object LoadModelConfig {
    def apply(
               c: com.typesafe.config.Config,
               parentPath: java.lang.String,
               $tsCfgValidator: $TsCfgValidator
             ): SimonaConfig.LoadModelConfig = {
      SimonaConfig.LoadModelConfig(
        scaling = $_reqDbl(parentPath, c, "scaling", $tsCfgValidator),
        uuids = $_L$_str(c.getList("uuids"), parentPath, $tsCfgValidator),
        modelBehaviour =
          $_reqStr(parentPath, c, "modelBehaviour", $tsCfgValidator),
        reference = $_reqStr(parentPath, c, "reference", $tsCfgValidator)
      )
    }

    private def $_reqStr(
                          parentPath: java.lang.String,
                          c: com.typesafe.config.Config,
                          path: java.lang.String,
                          $tsCfgValidator: $TsCfgValidator
                        ): java.lang.String = {
      if (c == null) null
      else
        try c.getString(path)
        catch {
          case e: com.typesafe.config.ConfigException =>
            $tsCfgValidator.addBadPath(parentPath + path, e)
            null
        }
    }

    private def $_reqDbl(
                          parentPath: java.lang.String,
                          c: com.typesafe.config.Config,
                          path: java.lang.String,
                          $tsCfgValidator: $TsCfgValidator
                        ): scala.Double = {
      if (c == null) 0
      else
        try c.getDouble(path)
        catch {
          case e: com.typesafe.config.ConfigException =>
            $tsCfgValidator.addBadPath(parentPath + path, e)
            0
        }
    }
  }

final case class FixedFeedInModelConfig(scaling: Double, uuids: List[String]) extends BaseModelConfig

  object FixedFeedInModelConfig {
    def apply(
               c: com.typesafe.config.Config,
               parentPath: java.lang.String,
               $tsCfgValidator: $TsCfgValidator
             ): SimonaConfig.FixedFeedInModelConfig = {
      SimonaConfig.FixedFeedInModelConfig(
        scaling = $_reqDbl(parentPath, c, "scaling", $tsCfgValidator),
        uuids = $_L$_str(c.getList("uuids"), parentPath, $tsCfgValidator),
      )
    }

    private def $_reqDbl(
                          parentPath: java.lang.String,
                          c: com.typesafe.config.Config,
                          path: java.lang.String,
                          $tsCfgValidator: $TsCfgValidator
                        ): scala.Double = {
      if (c == null) 0
      else
        try c.getDouble(path)
        catch {
          case e: com.typesafe.config.ConfigException =>
            $tsCfgValidator.addBadPath(parentPath + path, e)
            0
        }
    }
  }

```

This is a first draft of the concept for now but I hope the general idea becomes clear. Looking forward to read what you think about it.

Cheers,

Johannes 

**tl;dr**
- inheritance for shared objects 
- added `final` modifier to scala case classes for scala best practices 🤓

### PR DESCRIPTION
**Pull request by johanneshiry**
Resolves #64

### CODE REVIEW

**Comment by johanneshiry** [comment]
fixed the invalid imports - sorry for the issues - didn't event know that there is a travis-ci behind this as no reports have been published as checks here ...

File: src/main/scala/tscfg/generators/java/JavaGen.scala [hunk 1]
```diff
@@ -144,16 +151,34 @@ class JavaGen(genOpts: GenOpts) extends Generator(genOpts) {
...
-      s"""public ${if (isRoot) "" else "static "}class $classNameAdjusted {
-         |  $classDeclMembersStr$classMemberGettersStr
-         |  $membersStr
-         |  public $classNameAdjusted($ctorParams) {
-         |    $errHandlingDecl$ctorMembersStr$errHandlingDispatch
-         |  }$elemAccessorsStr
-         |$rootAuxClasses}
-         |""".stripMargin
-    }
+    val extendsString = abstractClassName.map("extends " + _).getOrElse("")
```
Comment (carueda) [inline src/main/scala/tscfg/generators/java/JavaGen.scala:154]: (1a) Include trailing  space here:
```scala
val extendsString = abstractClassName.map(cn => s"extends $cn ").getOrElse("")
```

File: src/main/scala/tscfg/generators/java/JavaGen.scala [hunk 2]
```diff
@@ -144,16 +151,34 @@ class JavaGen(genOpts: GenOpts) extends Generator(genOpts) {
...
+    val superString = abstractClassName.map(_ => "super(c, parentPath, $tsCfgValidator);").getOrElse("") // if parent class name is defined a super call is needed
+
+    val classStr =
+      ot match {
+        case _: ObjectType =>
+          s"""public ${
+            if (isRoot) "" else "static "
+          }class $classNameAdjusted $extendsString {
```
Comment (carueda) [inline src/main/scala/tscfg/generators/java/JavaGen.scala:162]: (1b) and remove it here (as it is adding an extra space right before the `{` for all cases where there's no abstract class involved:
```scala
}class $classNameAdjusted $extendsString{
```

File: src/main/scala/tscfg/generators/java/JavaGen.scala [hunk 3]
```diff
@@ -144,16 +151,34 @@ class JavaGen(genOpts: GenOpts) extends Generator(genOpts) {
...
-         |  $classDeclMembersStr$classMemberGettersStr
-         |  $membersStr
-         |  public $classNameAdjusted($ctorParams) {
-         |    $errHandlingDecl$ctorMembersStr$errHandlingDispatch
-         |  }$elemAccessorsStr
-         |$rootAuxClasses}
-         |""".stripMargin
-    }
+    val extendsString = abstractClassName.map("extends " + _).getOrElse("")
+    val superString = abstractClassName.map(_ => "super(c, parentPath, $tsCfgValidator);").getOrElse("") // if parent class name is defined a super call is needed
```
Comment (carueda) [inline src/main/scala/tscfg/generators/java/JavaGen.scala:155]: (2a) Include the newline and indentation here:
```scala
    // if parent class name is defined a super call is needed:
    val superString = abstractClassName.map(_ => "\n    super(c, parentPath, $tsCfgValidator);").getOrElse("") 
```

File: src/main/scala/tscfg/generators/java/JavaGen.scala [hunk 4]
```diff
@@ -144,16 +151,34 @@ class JavaGen(genOpts: GenOpts) extends Generator(genOpts) {
...
+
+    val classStr =
+      ot match {
+        case _: ObjectType =>
+          s"""public ${
+            if (isRoot) "" else "static "
+          }class $classNameAdjusted $extendsString {
+             |  $classDeclMembersStr$classMemberGettersStr
+             |  $membersStr
+             |  public $classNameAdjusted($ctorParams) {
```
Comment (carueda) [inline src/main/scala/tscfg/generators/java/JavaGen.scala:165]: (2b) and use it like this to avoid the empty line after the `{` that is being added to all other cases where there's no `super` involved:
```scala
  public $classNameAdjusted($ctorParams) {$superString
```

Comment (carueda) [reply src/main/scala/tscfg/generators/java/JavaGen.scala:165]: @johanneshiry Those observations (1) and (2) above are to avoid changing the java generation wrt to previous versions of tscfg for config specs not involving the new "abstract" feature.  I've seen user also committing the generated classes in version control and these adjustments, no only helps with a little better formatted code, but also avoids such users deal with unnecessary changes if running the new version of the generator.

File: src/main/scala/tscfg/model.scala [hunk 5]
```diff
@@ -16,61 +19,107 @@ object model {
...
-                     optional:      Boolean = false,
-                     default:       Option[String] = None,
-                     comments:      Option[String] = None
+  final case object AnnType{
+
+    val extendsPattern: Regex = """@\w+ extends ([a-zA-Z0-9]+)""".r
+
+    def isDefine(commentString: String): Boolean = commentString.trim.startsWith("@define")
+
+    def isParent(commentString: String): Boolean = commentString.trim.equals("@define_abstract")
```
Comment (carueda) [inline src/main/scala/tscfg/model.scala:82]: Please split `@define_abstract` so this is to be indicated with two separate tokens:`@define abstract`.  Reasons:
- you are already dealing with `@define extends` where the tokens as separated
- in a future version we may be adding, not only the already suggested `@define enum`, but also probably a variation of this "abstract" feature with for example `@define trait`.  (In fact, I was wondering if you would like to incorporate such variation here... but maybe too much for a single PR ;).

Comment (johanneshiry) [reply src/main/scala/tscfg/model.scala]: I'm not 100% sure if I got your comment on this correctly but I tried to solve  this. Let me short explaining why I decided for the finally implemented solution.

My first approach result has been: 
```scala
isDefine(commentString) && commentString.trim.endsWith("abstract")
```

but this would allow for e.g. `@define_foo_bar_abstract` or `@define bar foo abstract`. To avoid this and enforce the syntax we would like to have I ended up with the finally implemented solution which I think might be more precise on what we are expecting here 

```scala 
  def isParent(commentString: String): Boolean = if (isDefine(commentString)) {
      commentString.replace(DEFINE_STRING, "").trim.equals("abstract")
    } else
      false
```

I hope I got your comment right here. If not, pls let me know.

Comment (johanneshiry) [reply src/main/scala/tscfg/model.scala]: For your second suggestion on `@define trait`: I had the same idea during working on this PR. The only reason I did not add trait support (for now) was my uncertainty about the benefit of having the abstract class and trait support. 

I had the following concerns:
- trait support would be scala only
- I did not saw any benefit of the trait implementation over the abstract class implementation 

I'm open to add trait support to this PR as well if you think this would increase the benefit of the abstract object definition. Would you mind telling me what you think about these two concerns of me? Maybe I'm missing something?

**Comment by johanneshiry** [comment]
Thanks for the extensive explanation of the review comments. I tried to address them accordingly. For the `abstract class`, `trait` or `enum` discussion I'm open to add more features even in this PR. Maybe we could discuss the exact requirements of `enum` and the benefits of having `trait` support before?
