### PR TITLE
Consider inheritance interdependency for shared objects

### LINKED ISSUE #67: Consider inheritance tree in traversing members
I noticed some difficulties in traversing member structs when using the new inheritance feature (many thanks for that!). Think of my following example config:

```
#@define abstract
AbstractA {
  a: string
}

#@define extends AbstractA
ImplA {
  b: string
}
```

Parsing this config to Scala config class aborts with `IllegalArgumentException` thrown in `ModelBuilder:210`, as the parent of `ImplA` cannot be found.

Here is, what is happening: In `ModelBuilder:85` it is ensured, that at first the shared objects are processed and added to the name space, without any further distinction among the shared objects. In my case by incident at first `ImplA` definition and then `AbstractA` definition should be traversed. Therefore `AbstractA` is not known to the name space on attempt to add `ImplA` leading to the described exception.

I would propose to extend the ordering logic in `ModelBuilder:85` to utilize an inheritance tree of shared objects. This would also allow inheritance of abstract shared objects then, e.g.

```
AbstractA
-- AbstractAA
---- ImplAA
-- AbstractAB
---- ImplAB
...
```

and the logic wouldn't rely on the order in which the user provides the shared object definitions.

Additionally, this might come in handy for #66 of @johanneshiry as then case class members (leaf nodes) can easily be identified.

If I can provide you anything further for a better understanding of my issue, please just let me know. If you two wish for some support on this, please also just give me a little hint. 😉

### PR DESCRIPTION
**Pull request by ckittl**
This PR is meant to resolve #67.

Changes / features in the scope of this PR:

- [x] Allow for multi level inheritance (until #66 isn't resolved, all intermediate members need to be abstract)
- [x] Set up interdependency / inheritance tree
- [x] Ensure the graph is acyclic
- [x] Linearize the tree (considering Scala's linearization order?) --> @carueda Until now, a breadth-first-search is performed on the graph. Please share your wishes on this.
- [x] Implement "integration" tests for equivalent configs

### CODE REVIEW

**Comment by carueda** [comment]
@ckittl many thanks for your work!   I continue to be swamped in other commitments but shall take a closer look at all of this in due course. Thanks also for all the tests, super important.

Re ordering, well, no special wishes really, only some sound scheme. 

Re namespace, I'm referring to the nesting in the config spec: A define `A` can extend a define `B` if `B` is in the same nesting level (namespace) of `A` or in an enclosing one..  make sense?

**Comment by ckittl** [comment]
Okay, so if you'd ask me, I would say I'm ready for review. Please do not feel rushed, do the review whenever it suits you - I have enough other obligations as well. 😉 

If you miss anything or I didn't follow your workflow well, please just let me know - it's my first time using the "fork and PR"-workflow.

**Comment by carueda** [comment]
Thanks again for your dedication, and for your patience while I'm able to review, which I intend to start doing as soon as time permits.  Although with all past and new tests passing is a strong basis for merging, I of course want to understand the changes themselves.

**Comment by ckittl** [comment]
I tried to place some comments to describe, what I intend to do. If there remains anything unclear, I'm happy to provide additional information. 👍

File: src/main/scala/tscfg/generators/java/JavaGen.scala [hunk 1]
```diff
@@ -167,17 +167,19 @@ class JavaGen(genOpts: GenOpts) extends Generator(genOpts) {
           }class $classNameAdjusted $extendsString{
              |  $classDeclMembersStr$classMemberGettersStr
              |  $membersStr
-             |  public $classNameAdjusted($ctorParams) {$superString
+             |  public $classNameAdjusted($ctorParams) {
+             |    $superString
```
Comment (carueda) [inline src/main/scala/tscfg/generators/java/JavaGen.scala:171]: You have moved `$superString` to its own line, but this would generate an empty line in the output when there's no content captured there.  Although machine-generated, we have tried to generate code that is clean as much as practically possible.  Also, keep in mind that generated code is often also maintained under version control (I've seen this out there in the wild and in fact I do it myself), so an upgrade of the tscfg tool in client code would potentially generate unnecessary diffs just because of changes in spaces.  So, if you could review this kind of changes (and there might be other similar cases as with this `$superString`), that would be good. In general, please do no reformat any existing code that is unrelated with the PR/issue.

**Review by carueda — CHANGES_REQUESTED** [review]

File: src/main/scala/tscfg/generators/java/JavaGen.scala (hunk 1 above)
Comment (carueda) [reply src/main/scala/tscfg/generators/java/JavaGen.scala:171]: But you know what? ...  actually, maybe the time is coming to start integrating a more intelligent, automatic, and consistent formatting of the output so one can just focus on the correct semantics of the output and let other tools to take care of the formatting.

So, I'd say, do not worry about these adjustments.  After the merge I'll look into integrating [scalafmt](https://scalameta.org/scalafmt/docs/installation.html#standalone-library) for Scala, and  probably [google-java-format](https://github.com/google/google-java-format#as-a-library) for Java.  Thanks.

Comment (carueda) [reply src/main/scala/tscfg/generators/java/JavaGen.scala:171]: I just added all generated files to version control and pushed them into master.  Can you please merge that into your branch (you will need to first delete the ones you have on your side for the merge to proceed)?  Then, you can re-generate with your new code and use your favorite diff tool to see the differences.  To be clear, this is just to have an easier way to inspect changes in the generated code as the tool gets updated. Thanks,

File: build.sbt [hunk 2]
```diff
@@ -9,11 +9,12 @@ scalaVersion := "2.12.10"
...
-  "com.typesafe"          %  "config"         % "1.3.3",
-  "org.specs2"           %%  "specs2-core"    % "4.6.0" % "test",
+  "com.typesafe"           %  "config"                  % "1.3.3",
+  "org.specs2"             %%  "specs2-core"            % "4.6.0" % "test",
   "org.scala-lang.modules" %% "scala-collection-compat" % "2.1.4",
-  "org.json4s"           %%  "json4s-native"  % "3.6.7",
-  "com.google.code.gson"  %  "gson"           % "2.8.0"
+  "org.json4s"             %%  "json4s-native"          % "3.6.7",
+  "com.google.code.gson"   %  "gson"                    % "2.8.0",
+  "org.scala-graph"        %% "graph-core"              % "1.13.1"
```
Comment (carueda) [inline build.sbt:17]: Didn't think an extra library would be needed for the task of finding cycles....  but perhaps it's a very lightweight library anyway.

**Comment by ckittl** [comment]
Thanks for merging the PR! Unfortunately, I didn't have the time to address your review comments, until now. I assume, that you won't like me to address them anymore?!

**Comment by carueda** [comment]
Sorry, I should have probably waited a bit longer but they were rather simple changes and I figured why not just merge and take it from there.  You're welcome to look into some of the tests that I then commented out due to not being fully correct AFAICT (in fact, some were failing both on travis and locally (you know, with `+test` to try the two scala versions --  although, as  commented, the particular scala version is in general irrelevant -- it's more about the underlying non-determinism while generating the result linearization).
